name: grabit_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  injectable: ^2.5.2
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  logger: ^2.6.2
  intl: ^0.20.2
  sprung: ^3.0.1
  another_flushbar: ^1.12.32
  loading_animation_widget: ^1.3.0
  gap: ^3.0.1
  fast_cached_network_image: ^1.3.3+5
  lottie: ^3.3.1
  photo_view: ^0.15.0
  flutter_svg: ^2.2.1
  flutter_animate: ^4.5.2
  location: ^8.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/animations/


  # example:
  fonts:
    - family: Fredoka
      fonts:
      - asset: assets/fonts/Fredoka-Light.ttf
        weight: 300
      - asset: assets/fonts/Fredoka-Regular.ttf 
        weight: 400
      - asset: assets/fonts/Fredoka-Medium.ttf
        weight: 500
      - asset: assets/fonts/Fredoka-Bold.ttf
        weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
